//
//SPDX-License-Identifier: MIT
//
//Copyright (c) 2023, SCANOSS
//
//Permission is hereby granted, free of charge, to any person obtaining a copy
//of this software and associated documentation files (the "Software"), to deal
//in the Software without restriction, including without limitation the rights
//to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//copies of the Software, and to permit persons to whom the Software is
//furnished to do so, subject to the following conditions:
//
//The above copyright notice and this permission notice shall be included in
//all copies or substantial portions of the Software.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//THE SOFTWARE.

//*
// Geo Provenance definition details

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: scanoss/api/geoprovenance/v2/scanoss-geoprovenance.proto

package geoprovenancev2

import (
	context "context"
	commonv2 "github.com/scanoss/papi/api/commonv2"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GeoProvenance_Echo_FullMethodName                     = "/scanoss.api.provenance.v2.GeoProvenance/Echo"
	GeoProvenance_GetComponentContributors_FullMethodName = "/scanoss.api.provenance.v2.GeoProvenance/GetComponentContributors"
	GeoProvenance_GetComponentOrigin_FullMethodName       = "/scanoss.api.provenance.v2.GeoProvenance/GetComponentOrigin"
)

// GeoProvenanceClient is the client API for GeoProvenance service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeoProvenanceClient interface {
	// Standard echo
	Echo(ctx context.Context, in *commonv2.EchoRequest, opts ...grpc.CallOption) (*commonv2.EchoResponse, error)
	// Get component-level Geo Provenance based on contributor declared location
	GetComponentContributors(ctx context.Context, in *commonv2.PurlRequest, opts ...grpc.CallOption) (*ContributorResponse, error)
	// Get component-level Geo Provenance based on contributor origin commit times
	GetComponentOrigin(ctx context.Context, in *commonv2.PurlRequest, opts ...grpc.CallOption) (*OriginResponse, error)
}

type geoProvenanceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeoProvenanceClient(cc grpc.ClientConnInterface) GeoProvenanceClient {
	return &geoProvenanceClient{cc}
}

func (c *geoProvenanceClient) Echo(ctx context.Context, in *commonv2.EchoRequest, opts ...grpc.CallOption) (*commonv2.EchoResponse, error) {
	out := new(commonv2.EchoResponse)
	err := c.cc.Invoke(ctx, GeoProvenance_Echo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoProvenanceClient) GetComponentContributors(ctx context.Context, in *commonv2.PurlRequest, opts ...grpc.CallOption) (*ContributorResponse, error) {
	out := new(ContributorResponse)
	err := c.cc.Invoke(ctx, GeoProvenance_GetComponentContributors_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoProvenanceClient) GetComponentOrigin(ctx context.Context, in *commonv2.PurlRequest, opts ...grpc.CallOption) (*OriginResponse, error) {
	out := new(OriginResponse)
	err := c.cc.Invoke(ctx, GeoProvenance_GetComponentOrigin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeoProvenanceServer is the server API for GeoProvenance service.
// All implementations must embed UnimplementedGeoProvenanceServer
// for forward compatibility
type GeoProvenanceServer interface {
	// Standard echo
	Echo(context.Context, *commonv2.EchoRequest) (*commonv2.EchoResponse, error)
	// Get component-level Geo Provenance based on contributor declared location
	GetComponentContributors(context.Context, *commonv2.PurlRequest) (*ContributorResponse, error)
	// Get component-level Geo Provenance based on contributor origin commit times
	GetComponentOrigin(context.Context, *commonv2.PurlRequest) (*OriginResponse, error)
	mustEmbedUnimplementedGeoProvenanceServer()
}

// UnimplementedGeoProvenanceServer must be embedded to have forward compatible implementations.
type UnimplementedGeoProvenanceServer struct {
}

func (UnimplementedGeoProvenanceServer) Echo(context.Context, *commonv2.EchoRequest) (*commonv2.EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedGeoProvenanceServer) GetComponentContributors(context.Context, *commonv2.PurlRequest) (*ContributorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComponentContributors not implemented")
}
func (UnimplementedGeoProvenanceServer) GetComponentOrigin(context.Context, *commonv2.PurlRequest) (*OriginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComponentOrigin not implemented")
}
func (UnimplementedGeoProvenanceServer) mustEmbedUnimplementedGeoProvenanceServer() {}

// UnsafeGeoProvenanceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeoProvenanceServer will
// result in compilation errors.
type UnsafeGeoProvenanceServer interface {
	mustEmbedUnimplementedGeoProvenanceServer()
}

func RegisterGeoProvenanceServer(s grpc.ServiceRegistrar, srv GeoProvenanceServer) {
	s.RegisterService(&GeoProvenance_ServiceDesc, srv)
}

func _GeoProvenance_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv2.EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoProvenanceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoProvenance_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoProvenanceServer).Echo(ctx, req.(*commonv2.EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoProvenance_GetComponentContributors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv2.PurlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoProvenanceServer).GetComponentContributors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoProvenance_GetComponentContributors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoProvenanceServer).GetComponentContributors(ctx, req.(*commonv2.PurlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoProvenance_GetComponentOrigin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv2.PurlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoProvenanceServer).GetComponentOrigin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoProvenance_GetComponentOrigin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoProvenanceServer).GetComponentOrigin(ctx, req.(*commonv2.PurlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GeoProvenance_ServiceDesc is the grpc.ServiceDesc for GeoProvenance service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeoProvenance_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scanoss.api.provenance.v2.GeoProvenance",
	HandlerType: (*GeoProvenanceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _GeoProvenance_Echo_Handler,
		},
		{
			MethodName: "GetComponentContributors",
			Handler:    _GeoProvenance_GetComponentContributors_Handler,
		},
		{
			MethodName: "GetComponentOrigin",
			Handler:    _GeoProvenance_GetComponentOrigin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scanoss/api/geoprovenance/v2/scanoss-geoprovenance.proto",
}
