//
//SPDX-License-Identifier: MIT
//
//Copyright (c) 2023, SCANOSS
//
//Permission is hereby granted, free of charge, to any person obtaining a copy
//of this software and associated documentation files (the "Software"), to deal
//in the Software without restriction, including without limitation the rights
//to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//copies of the Software, and to permit persons to whom the Software is
//furnished to do so, subject to the following conditions:
//
//The above copyright notice and this permission notice shall be included in
//all copies or substantial portions of the Software.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//THE SOFTWARE.

//*
// Semgrep definition details

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: scanoss/api/semgrep/v2/scanoss-semgrep.proto

package semgrepv2

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	commonv2 "github.com/scanoss/papi/api/commonv2"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Security issue information detected by Semgrep analysis
type Issue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the Semgrep rule that detected this issue
	RuleID string `protobuf:"bytes,1,opt,name=ruleID,proto3" json:"ruleID,omitempty"`
	// Starting line number where the issue was detected
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// Ending line number where the issue was detected
	To string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	// Severity level of the security issue (e.g., "ERROR", "WARNING", "INFO")
	Severity      string `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescGZIP(), []int{0}
}

func (x *Issue) GetRuleID() string {
	if x != nil {
		return x.RuleID
	}
	return ""
}

func (x *Issue) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Issue) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Issue) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

// File containing security issues detected by Semgrep
type File struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MD5 hash of the file content for integrity verification
	FileMD5 string `protobuf:"bytes,1,opt,name=fileMD5,proto3" json:"fileMD5,omitempty"`
	// Relative path of the file within the component
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// List of security issues found in this file
	Issues        []*Issue `protobuf:"bytes,3,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescGZIP(), []int{1}
}

func (x *File) GetFileMD5() string {
	if x != nil {
		return x.FileMD5
	}
	return ""
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

// *
// [DEPRECATED] Semgrep issue response data (JSON payload)
// This message is deprecated. Use ComponentsSemgrepResponse instead for better component handling.
// Contains security issues detected by Semgrep analysis for components.
//
// Deprecated: Marked as deprecated in scanoss/api/semgrep/v2/scanoss-semgrep.proto.
type SemgrepResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Security analysis details for each requested component
	Purls []*SemgrepResponse_Purls `protobuf:"bytes,1,rep,name=purls,proto3" json:"purls,omitempty"`
	// Response status indicating success or failure of the request
	Status        *commonv2.StatusResponse `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemgrepResponse) Reset() {
	*x = SemgrepResponse{}
	mi := &file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemgrepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemgrepResponse) ProtoMessage() {}

func (x *SemgrepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemgrepResponse.ProtoReflect.Descriptor instead.
func (*SemgrepResponse) Descriptor() ([]byte, []int) {
	return file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescGZIP(), []int{2}
}

func (x *SemgrepResponse) GetPurls() []*SemgrepResponse_Purls {
	if x != nil {
		return x.Purls
	}
	return nil
}

func (x *SemgrepResponse) GetStatus() *commonv2.StatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

// Information about a component and its security issues
type ComponentIssueInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Package URL string identifying the component
	Purl string `protobuf:"bytes,1,opt,name=purl,proto3" json:"purl,omitempty"`
	// Version of the component being analyzed
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Version requirement specification (e.g., ">=1.0.0", "~2.1.0")
	Requirement string `protobuf:"bytes,3,opt,name=requirement,proto3" json:"requirement,omitempty"`
	// List of files containing security issues in this component
	Files         []*File `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentIssueInfo) Reset() {
	*x = ComponentIssueInfo{}
	mi := &file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentIssueInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentIssueInfo) ProtoMessage() {}

func (x *ComponentIssueInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentIssueInfo.ProtoReflect.Descriptor instead.
func (*ComponentIssueInfo) Descriptor() ([]byte, []int) {
	return file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescGZIP(), []int{3}
}

func (x *ComponentIssueInfo) GetPurl() string {
	if x != nil {
		return x.Purl
	}
	return ""
}

func (x *ComponentIssueInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ComponentIssueInfo) GetRequirement() string {
	if x != nil {
		return x.Requirement
	}
	return ""
}

func (x *ComponentIssueInfo) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

// *
// Components issue response data (JSON payload)
// Contains security issues detected by Semgrep analysis for multiple components.
// This is the current response format that replaces the deprecated SemgrepResponse.
type ComponentsIssueResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Security analysis details for each requested component
	Components []*ComponentIssueInfo `protobuf:"bytes,1,rep,name=components,proto3" json:"components,omitempty"`
	// Response status indicating success or failure of the request
	Status        *commonv2.StatusResponse `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentsIssueResponse) Reset() {
	*x = ComponentsIssueResponse{}
	mi := &file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentsIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentsIssueResponse) ProtoMessage() {}

func (x *ComponentsIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentsIssueResponse.ProtoReflect.Descriptor instead.
func (*ComponentsIssueResponse) Descriptor() ([]byte, []int) {
	return file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescGZIP(), []int{4}
}

func (x *ComponentsIssueResponse) GetComponents() []*ComponentIssueInfo {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *ComponentsIssueResponse) GetStatus() *commonv2.StatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

// *
// Component issue response data (JSON payload)
// Contains security issues detected by Semgrep analysis for a single component.
// This is the current response format that replaces the deprecated SemgrepResponse.
type ComponentIssueResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Security analysis details for the requested component
	Component *ComponentIssueInfo `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	// Response status indicating success or failure of the request
	Status        *commonv2.StatusResponse `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentIssueResponse) Reset() {
	*x = ComponentIssueResponse{}
	mi := &file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentIssueResponse) ProtoMessage() {}

func (x *ComponentIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentIssueResponse.ProtoReflect.Descriptor instead.
func (*ComponentIssueResponse) Descriptor() ([]byte, []int) {
	return file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescGZIP(), []int{5}
}

func (x *ComponentIssueResponse) GetComponent() *ComponentIssueInfo {
	if x != nil {
		return x.Component
	}
	return nil
}

func (x *ComponentIssueResponse) GetStatus() *commonv2.StatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

// Information about a given Package URL (PURL)
type SemgrepResponse_Purls struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Package URL string identifying the component
	Purl string `protobuf:"bytes,1,opt,name=purl,proto3" json:"purl,omitempty"`
	// Version of the component being analyzed
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// List of files containing security issues
	Files         []*File `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemgrepResponse_Purls) Reset() {
	*x = SemgrepResponse_Purls{}
	mi := &file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemgrepResponse_Purls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemgrepResponse_Purls) ProtoMessage() {}

func (x *SemgrepResponse_Purls) ProtoReflect() protoreflect.Message {
	mi := &file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemgrepResponse_Purls.ProtoReflect.Descriptor instead.
func (*SemgrepResponse_Purls) Descriptor() ([]byte, []int) {
	return file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescGZIP(), []int{2, 0}
}

func (x *SemgrepResponse_Purls) GetPurl() string {
	if x != nil {
		return x.Purl
	}
	return ""
}

func (x *SemgrepResponse_Purls) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SemgrepResponse_Purls) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_scanoss_api_semgrep_v2_scanoss_semgrep_proto protoreflect.FileDescriptor

const file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDesc = "" +
	"\n" +
	",scanoss/api/semgrep/v2/scanoss-semgrep.proto\x12\x16scanoss.api.semgrep.v2\x1a*scanoss/api/common/v2/scanoss-common.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"_\n" +
	"\x05Issue\x12\x16\n" +
	"\x06ruleID\x18\x01 \x01(\tR\x06ruleID\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\"k\n" +
	"\x04File\x12\x18\n" +
	"\afileMD5\x18\x01 \x01(\tR\afileMD5\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x125\n" +
	"\x06issues\x18\x03 \x03(\v2\x1d.scanoss.api.semgrep.v2.IssueR\x06issues\"\x84\x02\n" +
	"\x0fSemgrepResponse\x12C\n" +
	"\x05purls\x18\x01 \x03(\v2-.scanoss.api.semgrep.v2.SemgrepResponse.PurlsR\x05purls\x12=\n" +
	"\x06status\x18\x02 \x01(\v2%.scanoss.api.common.v2.StatusResponseR\x06status\x1ai\n" +
	"\x05Purls\x12\x12\n" +
	"\x04purl\x18\x01 \x01(\tR\x04purl\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x122\n" +
	"\x05files\x18\x03 \x03(\v2\x1c.scanoss.api.semgrep.v2.FileR\x05files:\x02\x18\x01\"\x98\x01\n" +
	"\x12ComponentIssueInfo\x12\x12\n" +
	"\x04purl\x18\x01 \x01(\tR\x04purl\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vrequirement\x18\x03 \x01(\tR\vrequirement\x122\n" +
	"\x05files\x18\x04 \x03(\v2\x1c.scanoss.api.semgrep.v2.FileR\x05files\"\xfa\x06\n" +
	"\x17ComponentsIssueResponse\x12J\n" +
	"\n" +
	"components\x18\x01 \x03(\v2*.scanoss.api.semgrep.v2.ComponentIssueInfoR\n" +
	"components\x12=\n" +
	"\x06status\x18\x02 \x01(\v2%.scanoss.api.common.v2.StatusResponseR\x06status:\xd3\x05\x92A\xcf\x05\n" +
	"\xcc\x05J\xc9\x05{\"components\":[{\"purl\":\"pkg:maven/org.apache.commons/commons-lang3\",\"version\":\"3.12.0\",\"requirement\":\"3.12.0\",\"files\":[{\"fileMD5\":\"a1b2c3d4e5f6\",\"path\":\"src/main/java/org/apache/commons/lang3/StringUtils.java\",\"issues\":[{\"ruleID\":\"java.lang.security.audit.crypto.weak-hash\",\"from\":\"156\",\"to\":\"159\",\"severity\":\"WARNING\"},{\"ruleID\":\"java.lang.security.audit.sql-injection.sql-injection\",\"from\":\"284\",\"to\":\"286\",\"severity\":\"ERROR\"}]},{\"fileMD5\":\"b2c3d4e5f6a1\",\"path\":\"src/main/java/org/apache/commons/lang3/Validate.java\",\"issues\":[{\"ruleID\":\"java.lang.security.audit.hardcoded-secret\",\"from\":\"95\",\"to\":\"95\",\"severity\":\"ERROR\"}]}]}],\"status\":{\"status\":\"SUCCESS\",\"message\":\"Security analysis completed successfully\"}}\"\xcc\x04\n" +
	"\x16ComponentIssueResponse\x12H\n" +
	"\tcomponent\x18\x01 \x01(\v2*.scanoss.api.semgrep.v2.ComponentIssueInfoR\tcomponent\x12=\n" +
	"\x06status\x18\x02 \x01(\v2%.scanoss.api.common.v2.StatusResponseR\x06status:\xa8\x03\x92A\xa4\x03\n" +
	"\xa1\x03J\x9e\x03{\"component\":{\"purl\":\"pkg:maven/org.apache.commons/commons-lang3\",\"version\":\"3.12.0\",\"requirement\":\"3.12.0\",\"files\":[{\"fileMD5\":\"a1b2c3d4e5f6\",\"path\":\"src/main/java/org/apache/commons/lang3/StringUtils.java\",\"issues\":[{\"ruleID\":\"java.lang.security.audit.sql-injection.sql-injection\",\"from\":\"284\",\"to\":\"286\",\"severity\":\"ERROR\"}]}]},\"status\":{\"status\":\"SUCCESS\",\"message\":\"Security analysis completed successfully\"}}2\x89\x04\n" +
	"\aSemgrep\x12l\n" +
	"\x04Echo\x12\".scanoss.api.common.v2.EchoRequest\x1a#.scanoss.api.common.v2.EchoResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v2/semgrep/echo\x12]\n" +
	"\tGetIssues\x12\".scanoss.api.common.v2.PurlRequest\x1a'.scanoss.api.semgrep.v2.SemgrepResponse\"\x03\x88\x02\x01\x12\x9a\x01\n" +
	"\x13GetComponentsIssues\x12(.scanoss.api.common.v2.ComponentsRequest\x1a/.scanoss.api.semgrep.v2.ComponentsIssueResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v2/semgrep/issues/components\x12\x93\x01\n" +
	"\x12GetComponentIssues\x12'.scanoss.api.common.v2.ComponentRequest\x1a..scanoss.api.semgrep.v2.ComponentIssueResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v2/semgrep/issues/componentB\x85\x02\x92A\xd0\x01\x12j\n" +
	"\x17SCANOSS Semgrep Service\"J\n" +
	"\x0fscanoss-semgrep\x12\"https://github.com/scanoss/semgrep\x1a\x13support@scanoss.com2\x032.0*\x01\x012\x10application/json:\x10application/jsonR;\n" +
	"\x03404\x124\n" +
	"*Returned when the resource does not exist.\x12\x06\n" +
	"\x04\x9a\x02\x01\aZ/github.com/scanoss/papi/api/semgrepv2;semgrepv2b\x06proto3"

var (
	file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescOnce sync.Once
	file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescData []byte
)

func file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescGZIP() []byte {
	file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescOnce.Do(func() {
		file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDesc), len(file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDesc)))
	})
	return file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescData
}

var file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_goTypes = []any{
	(*Issue)(nil),                      // 0: scanoss.api.semgrep.v2.Issue
	(*File)(nil),                       // 1: scanoss.api.semgrep.v2.File
	(*SemgrepResponse)(nil),            // 2: scanoss.api.semgrep.v2.SemgrepResponse
	(*ComponentIssueInfo)(nil),         // 3: scanoss.api.semgrep.v2.ComponentIssueInfo
	(*ComponentsIssueResponse)(nil),    // 4: scanoss.api.semgrep.v2.ComponentsIssueResponse
	(*ComponentIssueResponse)(nil),     // 5: scanoss.api.semgrep.v2.ComponentIssueResponse
	(*SemgrepResponse_Purls)(nil),      // 6: scanoss.api.semgrep.v2.SemgrepResponse.Purls
	(*commonv2.StatusResponse)(nil),    // 7: scanoss.api.common.v2.StatusResponse
	(*commonv2.EchoRequest)(nil),       // 8: scanoss.api.common.v2.EchoRequest
	(*commonv2.PurlRequest)(nil),       // 9: scanoss.api.common.v2.PurlRequest
	(*commonv2.ComponentsRequest)(nil), // 10: scanoss.api.common.v2.ComponentsRequest
	(*commonv2.ComponentRequest)(nil),  // 11: scanoss.api.common.v2.ComponentRequest
	(*commonv2.EchoResponse)(nil),      // 12: scanoss.api.common.v2.EchoResponse
}
var file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_depIdxs = []int32{
	0,  // 0: scanoss.api.semgrep.v2.File.issues:type_name -> scanoss.api.semgrep.v2.Issue
	6,  // 1: scanoss.api.semgrep.v2.SemgrepResponse.purls:type_name -> scanoss.api.semgrep.v2.SemgrepResponse.Purls
	7,  // 2: scanoss.api.semgrep.v2.SemgrepResponse.status:type_name -> scanoss.api.common.v2.StatusResponse
	1,  // 3: scanoss.api.semgrep.v2.ComponentIssueInfo.files:type_name -> scanoss.api.semgrep.v2.File
	3,  // 4: scanoss.api.semgrep.v2.ComponentsIssueResponse.components:type_name -> scanoss.api.semgrep.v2.ComponentIssueInfo
	7,  // 5: scanoss.api.semgrep.v2.ComponentsIssueResponse.status:type_name -> scanoss.api.common.v2.StatusResponse
	3,  // 6: scanoss.api.semgrep.v2.ComponentIssueResponse.component:type_name -> scanoss.api.semgrep.v2.ComponentIssueInfo
	7,  // 7: scanoss.api.semgrep.v2.ComponentIssueResponse.status:type_name -> scanoss.api.common.v2.StatusResponse
	1,  // 8: scanoss.api.semgrep.v2.SemgrepResponse.Purls.files:type_name -> scanoss.api.semgrep.v2.File
	8,  // 9: scanoss.api.semgrep.v2.Semgrep.Echo:input_type -> scanoss.api.common.v2.EchoRequest
	9,  // 10: scanoss.api.semgrep.v2.Semgrep.GetIssues:input_type -> scanoss.api.common.v2.PurlRequest
	10, // 11: scanoss.api.semgrep.v2.Semgrep.GetComponentsIssues:input_type -> scanoss.api.common.v2.ComponentsRequest
	11, // 12: scanoss.api.semgrep.v2.Semgrep.GetComponentIssues:input_type -> scanoss.api.common.v2.ComponentRequest
	12, // 13: scanoss.api.semgrep.v2.Semgrep.Echo:output_type -> scanoss.api.common.v2.EchoResponse
	2,  // 14: scanoss.api.semgrep.v2.Semgrep.GetIssues:output_type -> scanoss.api.semgrep.v2.SemgrepResponse
	4,  // 15: scanoss.api.semgrep.v2.Semgrep.GetComponentsIssues:output_type -> scanoss.api.semgrep.v2.ComponentsIssueResponse
	5,  // 16: scanoss.api.semgrep.v2.Semgrep.GetComponentIssues:output_type -> scanoss.api.semgrep.v2.ComponentIssueResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_init() }
func file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_init() {
	if File_scanoss_api_semgrep_v2_scanoss_semgrep_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDesc), len(file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_goTypes,
		DependencyIndexes: file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_depIdxs,
		MessageInfos:      file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes,
	}.Build()
	File_scanoss_api_semgrep_v2_scanoss_semgrep_proto = out.File
	file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_goTypes = nil
	file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_depIdxs = nil
}
