//
//SPDX-License-Identifier: MIT
//
//Copyright (c) 2023, SCANOSS
//
//Permission is hereby granted, free of charge, to any person obtaining a copy
//of this software and associated documentation files (the "Software"), to deal
//in the Software without restriction, including without limitation the rights
//to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//copies of the Software, and to permit persons to whom the Software is
//furnished to do so, subject to the following conditions:
//
//The above copyright notice and this permission notice shall be included in
//all copies or substantial portions of the Software.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//THE SOFTWARE.

//**
// semgrep definition details
//*

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: scanoss/api/semgrep/v2/scanoss-semgrep.proto

package semgrepv2

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	commonv2 "github.com/scanoss/papi/api/commonv2"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Semgrep issue response data (JSON payload)
type SemgrepResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cryptography details
	Purls []*SemgrepResponse_Purls `protobuf:"bytes,1,rep,name=purls,proto3" json:"purls,omitempty"`
	// Response status
	Status        *commonv2.StatusResponse `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemgrepResponse) Reset() {
	*x = SemgrepResponse{}
	mi := &file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemgrepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemgrepResponse) ProtoMessage() {}

func (x *SemgrepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemgrepResponse.ProtoReflect.Descriptor instead.
func (*SemgrepResponse) Descriptor() ([]byte, []int) {
	return file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescGZIP(), []int{0}
}

func (x *SemgrepResponse) GetPurls() []*SemgrepResponse_Purls {
	if x != nil {
		return x.Purls
	}
	return nil
}

func (x *SemgrepResponse) GetStatus() *commonv2.StatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

type SemgrepResponse_Issue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleID        string                 `protobuf:"bytes,1,opt,name=ruleID,proto3" json:"ruleID,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemgrepResponse_Issue) Reset() {
	*x = SemgrepResponse_Issue{}
	mi := &file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemgrepResponse_Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemgrepResponse_Issue) ProtoMessage() {}

func (x *SemgrepResponse_Issue) ProtoReflect() protoreflect.Message {
	mi := &file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemgrepResponse_Issue.ProtoReflect.Descriptor instead.
func (*SemgrepResponse_Issue) Descriptor() ([]byte, []int) {
	return file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SemgrepResponse_Issue) GetRuleID() string {
	if x != nil {
		return x.RuleID
	}
	return ""
}

func (x *SemgrepResponse_Issue) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SemgrepResponse_Issue) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SemgrepResponse_Issue) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type SemgrepResponse_File struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	FileMD5       string                   `protobuf:"bytes,1,opt,name=fileMD5,proto3" json:"fileMD5,omitempty"`
	Path          string                   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Issues        []*SemgrepResponse_Issue `protobuf:"bytes,3,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemgrepResponse_File) Reset() {
	*x = SemgrepResponse_File{}
	mi := &file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemgrepResponse_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemgrepResponse_File) ProtoMessage() {}

func (x *SemgrepResponse_File) ProtoReflect() protoreflect.Message {
	mi := &file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemgrepResponse_File.ProtoReflect.Descriptor instead.
func (*SemgrepResponse_File) Descriptor() ([]byte, []int) {
	return file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SemgrepResponse_File) GetFileMD5() string {
	if x != nil {
		return x.FileMD5
	}
	return ""
}

func (x *SemgrepResponse_File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SemgrepResponse_File) GetIssues() []*SemgrepResponse_Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

type SemgrepResponse_Purls struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Purl          string                  `protobuf:"bytes,1,opt,name=purl,proto3" json:"purl,omitempty"`
	Version       string                  `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Files         []*SemgrepResponse_File `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemgrepResponse_Purls) Reset() {
	*x = SemgrepResponse_Purls{}
	mi := &file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemgrepResponse_Purls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemgrepResponse_Purls) ProtoMessage() {}

func (x *SemgrepResponse_Purls) ProtoReflect() protoreflect.Message {
	mi := &file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemgrepResponse_Purls.ProtoReflect.Descriptor instead.
func (*SemgrepResponse_Purls) Descriptor() ([]byte, []int) {
	return file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescGZIP(), []int{0, 2}
}

func (x *SemgrepResponse_Purls) GetPurl() string {
	if x != nil {
		return x.Purl
	}
	return ""
}

func (x *SemgrepResponse_Purls) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SemgrepResponse_Purls) GetFiles() []*SemgrepResponse_File {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_scanoss_api_semgrep_v2_scanoss_semgrep_proto protoreflect.FileDescriptor

const file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDesc = "" +
	"\n" +
	",scanoss/api/semgrep/v2/scanoss-semgrep.proto\x12\x16scanoss.api.semgrep.v2\x1a*scanoss/api/common/v2/scanoss-common.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xee\x03\n" +
	"\x0fSemgrepResponse\x12C\n" +
	"\x05purls\x18\x01 \x03(\v2-.scanoss.api.semgrep.v2.SemgrepResponse.PurlsR\x05purls\x12=\n" +
	"\x06status\x18\x02 \x01(\v2%.scanoss.api.common.v2.StatusResponseR\x06status\x1a_\n" +
	"\x05Issue\x12\x16\n" +
	"\x06ruleID\x18\x01 \x01(\tR\x06ruleID\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x1a{\n" +
	"\x04File\x12\x18\n" +
	"\afileMD5\x18\x01 \x01(\tR\afileMD5\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12E\n" +
	"\x06issues\x18\x03 \x03(\v2-.scanoss.api.semgrep.v2.SemgrepResponse.IssueR\x06issues\x1ay\n" +
	"\x05Purls\x12\x12\n" +
	"\x04purl\x18\x01 \x01(\tR\x04purl\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12B\n" +
	"\x05files\x18\x03 \x03(\v2,.scanoss.api.semgrep.v2.SemgrepResponse.FileR\x05files2\xf8\x01\n" +
	"\aSemgrep\x12p\n" +
	"\x04Echo\x12\".scanoss.api.common.v2.EchoRequest\x1a#.scanoss.api.common.v2.EchoResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v2/semgrep/echo\x12{\n" +
	"\tGetIssues\x12\".scanoss.api.common.v2.PurlRequest\x1a'.scanoss.api.semgrep.v2.SemgrepResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v2/semgrep/issuesB\x85\x02\x92A\xd0\x01\x12j\n" +
	"\x17SCANOSS Semgrep Service\"J\n" +
	"\x0fscanoss-semgrep\x12\"https://github.com/scanoss/semgrep\x1a\x13support@scanoss.com2\x032.0*\x01\x012\x10application/json:\x10application/jsonR;\n" +
	"\x03404\x124\n" +
	"*Returned when the resource does not exist.\x12\x06\n" +
	"\x04\x9a\x02\x01\aZ/github.com/scanoss/papi/api/semgrepv2;semgrepv2b\x06proto3"

var (
	file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescOnce sync.Once
	file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescData []byte
)

func file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescGZIP() []byte {
	file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescOnce.Do(func() {
		file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDesc), len(file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDesc)))
	})
	return file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDescData
}

var file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_goTypes = []any{
	(*SemgrepResponse)(nil),         // 0: scanoss.api.semgrep.v2.SemgrepResponse
	(*SemgrepResponse_Issue)(nil),   // 1: scanoss.api.semgrep.v2.SemgrepResponse.Issue
	(*SemgrepResponse_File)(nil),    // 2: scanoss.api.semgrep.v2.SemgrepResponse.File
	(*SemgrepResponse_Purls)(nil),   // 3: scanoss.api.semgrep.v2.SemgrepResponse.Purls
	(*commonv2.StatusResponse)(nil), // 4: scanoss.api.common.v2.StatusResponse
	(*commonv2.EchoRequest)(nil),    // 5: scanoss.api.common.v2.EchoRequest
	(*commonv2.PurlRequest)(nil),    // 6: scanoss.api.common.v2.PurlRequest
	(*commonv2.EchoResponse)(nil),   // 7: scanoss.api.common.v2.EchoResponse
}
var file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_depIdxs = []int32{
	3, // 0: scanoss.api.semgrep.v2.SemgrepResponse.purls:type_name -> scanoss.api.semgrep.v2.SemgrepResponse.Purls
	4, // 1: scanoss.api.semgrep.v2.SemgrepResponse.status:type_name -> scanoss.api.common.v2.StatusResponse
	1, // 2: scanoss.api.semgrep.v2.SemgrepResponse.File.issues:type_name -> scanoss.api.semgrep.v2.SemgrepResponse.Issue
	2, // 3: scanoss.api.semgrep.v2.SemgrepResponse.Purls.files:type_name -> scanoss.api.semgrep.v2.SemgrepResponse.File
	5, // 4: scanoss.api.semgrep.v2.Semgrep.Echo:input_type -> scanoss.api.common.v2.EchoRequest
	6, // 5: scanoss.api.semgrep.v2.Semgrep.GetIssues:input_type -> scanoss.api.common.v2.PurlRequest
	7, // 6: scanoss.api.semgrep.v2.Semgrep.Echo:output_type -> scanoss.api.common.v2.EchoResponse
	0, // 7: scanoss.api.semgrep.v2.Semgrep.GetIssues:output_type -> scanoss.api.semgrep.v2.SemgrepResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_init() }
func file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_init() {
	if File_scanoss_api_semgrep_v2_scanoss_semgrep_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDesc), len(file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_goTypes,
		DependencyIndexes: file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_depIdxs,
		MessageInfos:      file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_msgTypes,
	}.Build()
	File_scanoss_api_semgrep_v2_scanoss_semgrep_proto = out.File
	file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_goTypes = nil
	file_scanoss_api_semgrep_v2_scanoss_semgrep_proto_depIdxs = nil
}
