name: Protoc - Compile
# This workflow will build the go/python/javascript APIs for the modified protos

on:
  workflow_dispatch:
  push:
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get tags to allow build script to get build version

      - name: Build Go Protobuf
        run: make build_go

      - name: Build Go Protobuf
        run: make build_python

      - name: Build Go Protobuf
        run: make build_js

      - name: List
        run: |
          tree python
          tree javascript
