name: Protoc - Golang
# This workflow will produce the golang APIs for the modified protos

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get tags to allow build script to get build version

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Install Protoc-gen-go plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest

      - name: Build
        run: make build_go
